import Navbar from "@/app/ui/front/navbar/navbar"
import Footer from "@/app/ui/front/footer/footer"
import { Toaster } from '@/app/ui/front/toaster/toaster'
import Providers from '@/app/ui/front/provider/providers' 
import '@/app/globals.css' 

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        <main className='flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]'>
          <div className='flex-1 flex flex-col h-full'>
            <Providers>{children}</Providers>
          </div>
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  )
}
