import Navbar from "@/app/ui/dashboard/navbar/navbar.jsx"
import Sidebar from "@/app/ui/dashboard/sidebar/sidebar.jsx"  

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Sidebar/>
      </body>
    </html>
  )
}
